### ISSUE TITLE
Could the Docker Hub image be updated please?

### ISSUE THREAD

**Issue by marnovdm** [Qarj/webinject-docker#2]
Hello,

Could you please publish the latest version (with https://github.com/Qarj/webimblaze-docker/pull/1) to https://hub.docker.com/r/qarj/webimblaze/tags? That would make it easy for everyone to test the latest WebImblaze version locally in Docker.

Greets Marno

**Comment by Qarj** [comment]
Hey Marno, I've pushed a new build, let me know if it is working for you...

**Comment by marnovdm** [comment]
Just tested here and seems to be updated correctly, nice! Thanks for the quick response (again!).

**Comment by Qarj** [comment]
No worries, best of luck with it :)
